### ISSUE TITLE
希望增加bilibili直播

### ISSUE THREAD

**Issue by feilongfl** [XIAZY/plugin.kogumi#1]
我找了bilibili的接口，并且用fish实现了mplayer播放，但是我不会用python吧这个功能变成插件。主要是最后一步带ua和302的播放地址我不知道应该怎么处理。

[fish+mplayer实现直播代码](https://gist.github.com/feilongfl/42600e62f5ec5efd3ebfe85058e14020)

**Comment by XIAZY** [comment]
可能是没有办法了，kodi没有提供相应的API

Sent from my iPhone

在 2018年1月29日，01:07，fei long <notifications@github.com<mailto:notifications@github.com>> 写道：


我找了bilibili的接口，并且用fish实现了mplayer播放，但是我不会用python吧这个功能变成插件。主要是最后一部带ua和302的播放地址我不知道应该怎么处理。

gist<https://gist.github.com/feilongfl/42600e62f5ec5efd3ebfe85058e14020>

**Comment by feilongfl** [comment]
好吧，我看看能不能有别的实现方法
